/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List staff for login selection UI
         * @description Device-authenticated only.
         */
        get: operations["authListStaff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login-pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Staff PIN sign-in
         * @description Device-authenticated only. Returns a staff session token. Rate limited per device.
         */
        post: operations["authLoginPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff sign-out */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current staff session */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate device headers and return device metadata */
        get: operations["devicesMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List devices
         * @description Admin only.
         */
        get: operations["adminDevicesList"];
        put?: never;
        /**
         * Create device and provision token
         * @description Admin only. Returns the raw provisioned device token once.
         */
        post: operations["adminDevicesCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update device (enable/disable/rename/kind)
         * @description Admin only. Disabling a device force-closes any active register session for that device.
         */
        patch: operations["adminDevicesUpdate"];
        trace?: never;
    };
    "/registers/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Register availability for register numbers 1..3 */
        get: operations["registersAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register-sessions/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a register session
         * @description Uses a uniqueness constraint to prevent multiple active sessions per register.
         */
        post: operations["registerSessionsOpen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register-sessions/{id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heartbeat for an active register session
         * @description Client target is every 30s; server TTL is configurable.
         */
        post: operations["registerSessionsHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register-sessions/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close a register session
         * @description Only the staff member who opened the session can close it. Admins must use force sign-out.
         */
        post: operations["registerSessionsClose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register-sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active register session for a register number */
        get: operations["registerSessionsActive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search customers */
        get: operations["customersSearch"];
        put?: never;
        /** Create customer */
        post: operations["customersCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active visit for a customer */
        get: operations["visitsActive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open a visit */
        post: operations["visitsOpen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew a visit */
        post: operations["visitsRenew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign inventory item to visit */
        post: operations["visitsAssign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a visit */
        post: operations["visitsClose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agreements/{visitId}/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture agreement for a visit */
        post: operations["agreementsCapture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List waitlist entries */
        get: operations["waitlistList"];
        put?: never;
        /** Create waitlist entry */
        post: operations["waitlistCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/waitlist/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel waitlist entry */
        post: operations["waitlistCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create inventory hold */
        post: operations["holdsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holds/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release inventory hold */
        post: operations["holdsRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upgrades/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create upgrade offer */
        post: operations["upgradesOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upgrades/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept upgrade offer */
        post: operations["upgradesAccept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upgrades/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline upgrade offer */
        post: operations["upgradesDecline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/{visitId}/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request checkout */
        post: operations["checkoutRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/{visitId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete checkout */
        post: operations["checkoutComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inventory items */
        get: operations["inventoryList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an inventory item */
        get: operations["inventoryGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/items/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update inventory item status */
        patch: operations["inventoryUpdateStatus"];
        trace?: never;
    };
    "/keys/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan a key tag */
        post: operations["keysScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cleaning/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a cleaning batch and transition statuses
         * @description If tagCodes are provided, itemIds are ignored. Result tagCode is null when itemIds are used; itemId is null when a tag scan fails or is unassigned.
         */
        post: operations["cleaningBatchCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/inventory/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create inventory item
         * @description Admin only.
         */
        post: operations["adminInventoryCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/key-tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update key tag assignment or enablement
         * @description Admin only.
         */
        patch: operations["adminKeyTagsUpdate"];
        trace?: never;
    };
    "/admin/register-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active register sessions (registers 1..3)
         * @description Admin only. Always returns entries for registers 1..3.
         */
        get: operations["adminRegisterSessionsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/register-sessions/{registerNumber}/force-signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force sign-out of a register session
         * @description Admin only. Idempotent if already signed out.
         */
        post: operations["adminRegisterSessionsForceSignout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit log entries
         * @description Admin only. Cursor pagination uses (created_at, id) encoded as base64url JSON.
         */
        get: operations["adminAuditList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            message: string;
            /** @enum {string} */
            code?: "DEVICE_UNAUTHORIZED" | "DEVICE_DISABLED" | "DEVICE_NOT_FOUND" | "STAFF_UNAUTHORIZED" | "STAFF_SESSION_EXPIRED" | "STAFF_DISABLED" | "FORBIDDEN" | "VALIDATION_ERROR" | "RATE_LIMITED" | "REGISTER_SESSION_NOT_FOUND" | "REGISTER_SESSION_NOT_ACTIVE" | "REGISTER_ACTIVE_CONFLICT" | "DEVICE_ACTIVE_CONFLICT" | "INVENTORY_NOT_FOUND" | "INVALID_STATUS_TRANSITION" | "KEY_TAG_NOT_FOUND" | "KEY_TAG_DISABLED" | "KEY_TAG_ASSIGNMENT_CONFLICT" | "CUSTOMER_NOT_FOUND" | "VISIT_NOT_FOUND" | "VISIT_ALREADY_ACTIVE" | "VISIT_MAX_DURATION_EXCEEDED" | "INVENTORY_UNAVAILABLE_FOR_ASSIGNMENT" | "AGREEMENT_ALREADY_CAPTURED" | "WAITLIST_NOT_FOUND" | "HOLD_NOT_FOUND" | "HOLD_CONFLICT" | "HOLD_EXPIRED" | "UPGRADE_NOT_FOUND" | "UPGRADE_INVALID_FROM" | "UPGRADE_EXPIRED" | "UPGRADE_ALREADY_DECIDED" | "CHECKOUT_ALREADY_COMPLETED";
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            /** Format: date-time */
            time: string;
        };
        /** @enum {integer} */
        RegisterNumber: 1 | 2 | 3;
        /** @enum {string} */
        DeviceKind: "register" | "kiosk" | "office";
        /** @enum {string} */
        VisitStatus: "ACTIVE" | "CLOSED";
        /** @enum {string} */
        AgreementStatus: "SIGNED" | "BYPASSED";
        /** @enum {string} */
        AgreementMethod: "KIOSK" | "REGISTER" | "ADMIN";
        /** @enum {string} */
        WaitlistRequestedType: "room" | "locker" | "any";
        /** @enum {string} */
        WaitlistStatus: "OPEN" | "CANCELLED" | "FULFILLED";
        /** @enum {string} */
        HoldStatus: "ACTIVE" | "RELEASED" | "EXPIRED";
        /** @enum {string} */
        UpgradeStatus: "PENDING" | "ACCEPTED" | "DECLINED" | "EXPIRED";
        /** @enum {string} */
        CheckoutMethod: "KIOSK" | "REGISTER" | "ADMIN";
        /** @enum {string} */
        InventoryItemType: "room" | "locker";
        /** @enum {string} */
        InventoryStatus: "AVAILABLE" | "OCCUPIED" | "DIRTY" | "CLEANING" | "OUT_OF_SERVICE";
        DeviceDTO: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["DeviceKind"];
            enabled: boolean;
            /** Format: date-time */
            lastSeenAt: string | null;
        };
        CustomerDTO: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            displayName: string | null;
            phone: string | null;
            email: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CustomerListResponse: {
            items: components["schemas"]["CustomerDTO"][];
        };
        CreateCustomerRequest: {
            firstName: string;
            lastName: string;
            displayName?: string | null;
            phone?: string | null;
            email?: string | null;
        };
        VisitDTO: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            customerId: string;
            status: components["schemas"]["VisitStatus"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            plannedEndAt: string;
            /** Format: date-time */
            closedAt: string | null;
            initialDurationMinutes: number;
            maxTotalDurationMinutes: number;
            renewalTotalMinutes: number;
        };
        VisitNullableResponse: {
            visit: components["schemas"]["VisitDTO"];
        };
        OpenVisitRequest: {
            /** Format: uuid */
            customerId: string;
        };
        RenewVisitRequest: {
            /** @enum {integer} */
            durationMinutes: 120 | 360;
        };
        AssignVisitRequest: {
            /** Format: uuid */
            inventoryItemId: string;
        };
        VisitAssignmentDTO: {
            /** Format: uuid */
            visitId: string;
            /** Format: uuid */
            inventoryItemId: string;
            /** Format: date-time */
            assignedAt: string;
            /** Format: date-time */
            releasedAt: string | null;
        };
        AgreementDTO: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            visitId: string;
            status: components["schemas"]["AgreementStatus"];
            /** Format: date-time */
            capturedAt: string;
            method: components["schemas"]["AgreementMethod"];
            metadata: {
                [key: string]: unknown;
            };
        };
        WaitlistEntryDTO: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            customerId: string;
            requestedType: components["schemas"]["WaitlistRequestedType"];
            status: components["schemas"]["WaitlistStatus"];
            notes: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WaitlistListResponse: {
            items: components["schemas"]["WaitlistEntryDTO"][];
        };
        CreateWaitlistRequest: {
            /** Format: uuid */
            customerId: string;
            requestedType: components["schemas"]["WaitlistRequestedType"];
            notes?: string | null;
        };
        HoldDTO: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            inventoryItemId: string;
            /** Format: uuid */
            visitId: string | null;
            /** Format: uuid */
            waitlistEntryId: string | null;
            status: components["schemas"]["HoldStatus"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateHoldRequest: {
            /** Format: uuid */
            inventoryItemId: string;
            /** Format: uuid */
            visitId?: string | null;
            /** Format: uuid */
            waitlistEntryId?: string | null;
            /** Format: date-time */
            expiresAt: string;
        };
        UpgradeOfferDTO: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            visitId: string;
            /** Format: uuid */
            fromInventoryItemId: string;
            /** @enum {string} */
            toInventoryType: "room" | "locker";
            status: components["schemas"]["UpgradeStatus"];
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateUpgradeOfferRequest: {
            /** Format: uuid */
            visitId: string;
            /** Format: uuid */
            fromInventoryItemId: string;
            /** @enum {string} */
            toInventoryType: "room" | "locker";
            /** Format: date-time */
            expiresAt: string;
        };
        CheckoutEventDTO: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            visitId: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            completedAt: string | null;
            method: components["schemas"]["CheckoutMethod"];
        };
        CheckoutRequest: {
            method: components["schemas"]["CheckoutMethod"];
        };
        CaptureAgreementRequest: {
            status: components["schemas"]["AgreementStatus"];
            method: components["schemas"]["AgreementMethod"];
            metadata?: {
                [key: string]: unknown;
            };
        };
        InventoryItemDTO: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["InventoryItemType"];
            name: string;
            status: components["schemas"]["InventoryStatus"];
            notes: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        InventoryListResponse: {
            items: components["schemas"]["InventoryItemDTO"][];
        };
        UpdateInventoryStatusRequest: {
            toStatus: components["schemas"]["InventoryStatus"];
            note?: string | null;
        };
        CreateInventoryItemRequest: {
            type: components["schemas"]["InventoryItemType"];
            name: string;
            status?: components["schemas"]["InventoryStatus"];
            notes?: string | null;
        };
        KeyTagDTO: {
            /** Format: uuid */
            id: string;
            tagCode: string;
            /** Format: uuid */
            assignedToItemId: string | null;
            enabled: boolean;
        };
        KeyScanRequest: {
            tagCode: string;
        };
        KeyScanResponse: {
            keyTag: components["schemas"]["KeyTagDTO"];
            item: components["schemas"]["InventoryItemDTO"];
        };
        UpdateKeyTagRequest: {
            enabled?: boolean;
            /** Format: uuid */
            assignedToItemId?: string | null;
        };
        /** @enum {string} */
        CleaningTargetStatus: "CLEANING" | "AVAILABLE";
        CleaningBatchRequest: {
            itemIds?: string[];
            tagCodes?: string[];
            toStatus: components["schemas"]["CleaningTargetStatus"];
        };
        CleaningBatchResult: {
            /** Format: uuid */
            itemId: string | null;
            tagCode: string | null;
            /** @enum {string} */
            status: "UPDATED" | "SKIPPED" | "FAILED";
            message?: string;
        };
        CleaningBatchResponse: {
            /** Format: uuid */
            batchId: string;
            results: components["schemas"]["CleaningBatchResult"][];
        };
        DeviceListResponse: {
            devices: components["schemas"]["DeviceDTO"][];
        };
        CreateDeviceRequest: {
            name: string;
            kind: components["schemas"]["DeviceKind"];
            /** @default true */
            enabled: boolean;
        };
        ProvisionDeviceResponse: {
            device: components["schemas"]["DeviceDTO"];
            /** @description Raw device token (returned only at issuance). */
            deviceToken: string;
        };
        UpdateDeviceRequest: {
            name?: string;
            kind?: components["schemas"]["DeviceKind"];
            enabled?: boolean;
        };
        /** @enum {string} */
        StaffRole: "staff" | "admin";
        StaffListItem: {
            /** Format: uuid */
            id: string;
            identifier: string;
            name: string;
            role: components["schemas"]["StaffRole"];
        };
        StaffListResponse: {
            staff: components["schemas"]["StaffListItem"][];
        };
        StaffLoginRequest: {
            identifier: string;
            /** Format: password */
            pin: string;
        };
        StaffSessionDTO: {
            /** Format: uuid */
            staffId: string;
            role: components["schemas"]["StaffRole"];
            /** Format: uuid */
            deviceId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        StaffLoginResponse: {
            session: components["schemas"]["StaffSessionDTO"];
            /** @description Opaque session token (returned only at issuance). */
            sessionToken: string;
        };
        RegisterSessionDTO: {
            /** Format: uuid */
            id: string;
            registerNumber: components["schemas"]["RegisterNumber"];
            /** Format: uuid */
            staffId: string;
            /** Format: uuid */
            deviceId: string;
            /** @enum {string} */
            status: "ACTIVE" | "ENDED";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            lastHeartbeatAt: string;
            /** Format: date-time */
            endedAt?: string | null;
            /** @enum {string|null} */
            endedReason?: "STAFF_CLOSED" | "FORCED_SIGN_OUT" | "TTL_EXPIRED" | null;
        };
        RegisterSessionNullableResponse: {
            session: components["schemas"]["RegisterSessionDTO"];
        };
        RegisterAvailabilityItem: {
            registerNumber: components["schemas"]["RegisterNumber"];
            available: boolean;
            /** Format: uuid */
            activeSessionId?: string | null;
        };
        RegisterAvailabilityResponse: {
            registers: components["schemas"]["RegisterAvailabilityItem"][];
        };
        OpenRegisterSessionRequest: {
            registerNumber: components["schemas"]["RegisterNumber"];
        };
        /** @description note is required when reason is OTHER. */
        CloseRegisterSessionRequest: {
            /** @enum {string} */
            reason: "STAFF_SIGN_OUT" | "SHIFT_END" | "OTHER";
            note?: string | null;
        };
        /** @description note is required when reason is OTHER. */
        ForceSignOutRequest: {
            /** @enum {string} */
            reason: "SECURITY" | "DEVICE_LOST" | "POLICY" | "OTHER";
            note?: string | null;
        };
        AdminRegisterSessionSlot: {
            registerNumber: components["schemas"]["RegisterNumber"];
            session: components["schemas"]["RegisterSessionDTO"];
        };
        AdminRegisterSessionsResponse: {
            registers: components["schemas"]["AdminRegisterSessionSlot"][];
        };
        AuditLog: {
            /** Format: uuid */
            id: string;
            action: string;
            entityType: string;
            /** Format: uuid */
            entityId: string;
            /** Format: uuid */
            actorStaffId: string | null;
            /** Format: uuid */
            actorDeviceId: string | null;
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        AuditListResponse: {
            items: components["schemas"]["AuditLog"][];
            nextCursor: string | null;
        };
    };
    responses: {
        /** @description Error */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            500: components["responses"]["ErrorResponse"];
        };
    };
    authListStaff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Staff list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffListResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    authLoginPin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffLoginRequest"];
            };
        };
        responses: {
            /** @description Staff session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffLoginResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            429: components["responses"]["ErrorResponse"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current staff session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffSessionDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    devicesMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    adminDevicesList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    adminDevicesCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceRequest"];
            };
        };
        responses: {
            /** @description Device created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionDeviceResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    adminDevicesUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceRequest"];
            };
        };
        responses: {
            /** @description Updated device */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    registersAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Register availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterAvailabilityResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    registerSessionsOpen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenRegisterSessionRequest"];
            };
        };
        responses: {
            /** @description Register session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterSessionDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    registerSessionsHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Register session updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterSessionDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    registerSessionsClose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRegisterSessionRequest"];
            };
        };
        responses: {
            /** @description Register session closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterSessionDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    registerSessionsActive: {
        parameters: {
            query: {
                registerNumber: components["schemas"]["RegisterNumber"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active register session or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterSessionNullableResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    customersSearch: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerListResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    customersCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerRequest"];
            };
        };
        responses: {
            /** @description Customer created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    visitsActive: {
        parameters: {
            query: {
                customerId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active visit or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitNullableResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    visitsOpen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenVisitRequest"];
            };
        };
        responses: {
            /** @description Visit opened */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    visitsRenew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewVisitRequest"];
            };
        };
        responses: {
            /** @description Visit renewed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    visitsAssign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignVisitRequest"];
            };
        };
        responses: {
            /** @description Assignment created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitAssignmentDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    visitsClose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visit closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    agreementsCapture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visitId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureAgreementRequest"];
            };
        };
        responses: {
            /** @description Agreement captured */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    waitlistList: {
        parameters: {
            query?: {
                status?: components["schemas"]["WaitlistStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Waitlist entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistListResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    waitlistCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWaitlistRequest"];
            };
        };
        responses: {
            /** @description Waitlist entry created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistEntryDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    waitlistCancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Waitlist entry cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistEntryDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    holdsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHoldRequest"];
            };
        };
        responses: {
            /** @description Hold created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    holdsRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hold released */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    upgradesOffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUpgradeOfferRequest"];
            };
        };
        responses: {
            /** @description Upgrade offer created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpgradeOfferDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    upgradesAccept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upgrade offer accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpgradeOfferDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    upgradesDecline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upgrade offer declined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpgradeOfferDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    checkoutRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visitId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Checkout requested */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutEventDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    checkoutComplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checkout completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutEventDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    inventoryList: {
        parameters: {
            query?: {
                type?: components["schemas"]["InventoryItemType"];
                status?: components["schemas"]["InventoryStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inventory items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryListResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    inventoryGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inventory item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemDTO"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    inventoryUpdateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInventoryStatusRequest"];
            };
        };
        responses: {
            /** @description Inventory item updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    keysScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyScanRequest"];
            };
        };
        responses: {
            /** @description Key scan result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyScanResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    cleaningBatchCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleaningBatchRequest"];
            };
        };
        responses: {
            /** @description Cleaning batch result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleaningBatchResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    adminInventoryCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInventoryItemRequest"];
            };
        };
        responses: {
            /** @description Inventory item created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItemDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    adminKeyTagsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKeyTagRequest"];
            };
        };
        responses: {
            /** @description Key tag updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyTagDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    adminRegisterSessionsList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Register session slots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRegisterSessionsResponse"];
                };
            };
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
    adminRegisterSessionsForceSignout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                registerNumber: components["schemas"]["RegisterNumber"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForceSignOutRequest"];
            };
        };
        responses: {
            /** @description Register session updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterSessionDTO"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    adminAuditList: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                entityType?: string;
                entityId?: string;
                actorStaffId?: string;
                action?: string;
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            401: components["responses"]["ErrorResponse"];
            403: components["responses"]["ErrorResponse"];
        };
    };
}
